# Generated by Django 4.2.5 on 2023-11-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(upload_to='')),
                ('restaurant', models.CharField(choices=[('restaurant1', 'restaurant1'), ('restaurant2', 'restaurant2'), ('restaurant3', 'restaurant3'), ('restaurant4', 'restaurant4'), ('restaurant5', 'restaurant5'), ('restaurant6', 'restaurant6')], max_length=50)),
                ('active', models.BooleanField()),
            ],
        ),
    ]
