# Generated by Django 4.2.5 on 2023-11-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovingData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('count', models.IntegerField()),
            ],
        ),
    ]
