# Generated by Django 4.2.5 on 2023-11-13 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_movingdata_id_alter_movingdata_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movingtoorders',
            fields=[
                ('restaurant', models.CharField(max_length=50)),
                ('totalamount', models.IntegerField(primary_key=True, serialize=False)),
                ('time', models.TimeField(default=datetime.datetime.now, editable=False)),
                ('date', models.DateField(default=datetime.datetime.now, editable=False)),
            ],
        ),
    ]
