# Generated by Django 4.2.5 on 2023-11-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_movingtoorders'),
    ]

    operations = [
        migrations.AddField(
            model_name='movingdata',
            name='restaurant',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
    ]
