# Generated by Django 4.2.5 on 2023-11-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_movingdata_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='movingtoorders',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='movingtoorders',
            name='totalamount',
            field=models.IntegerField(),
        ),
    ]
