# Generated by Django 4.2.5 on 2023-11-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_movingtoorders_id_alter_movingtoorders_totalamount'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.CharField(max_length=50)),
                ('totalamount', models.IntegerField()),
                ('time', models.TimeField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='movingtoorders',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
