# Generated by Django 4.2.5 on 2023-11-17 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_moveddata_alter_movingtoorders_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moveddata',
            options={'ordering': ['-id']},
        ),
    ]
