# Generated by Django 5.0 on 2023-12-17 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_alter_moveddata_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=50)),
                ('count', models.IntegerField()),
                ('in_order', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name=datetime.datetime(2023, 12, 17, 15, 52, 32, 435724))),
                ('time', models.TimeField(verbose_name=datetime.datetime(2023, 12, 17, 15, 52, 32, 435724))),
                ('status', models.BooleanField()),
                ('delivery_time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rate', models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=50)),
                ('average_order_time', models.IntegerField()),
                ('average_price', models.IntegerField()),
                ('image', models.ImageField(upload_to='photos/resturants/%y/%m/%d')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='MovedData',
        ),
        migrations.DeleteModel(
            name='MovingData',
        ),
        migrations.DeleteModel(
            name='Movingtoorders',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
