# Generated by Django 5.0 on 2023-12-17 13:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_product_alter_order_date_alter_order_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='pages.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2023, 12, 17, 15, 8, 5, 666152)),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.TimeField(verbose_name=datetime.datetime(2023, 12, 17, 15, 8, 5, 666152)),
        ),
    ]
