# Generated by Django 5.0 on 2023-12-17 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_alter_cartproduct_product_alter_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(auto_created=True, verbose_name=datetime.datetime(2023, 12, 17, 15, 27, 30, 586305)),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.TimeField(auto_created=True, verbose_name=datetime.datetime(2023, 12, 17, 15, 27, 30, 586305)),
        ),
    ]
