# Generated by Django 5.0 on 2023-12-18 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_remove_product_restaurant_restaurant_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(editable=False, verbose_name=datetime.datetime(2023, 12, 18, 18, 43, 46, 754054)),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.TimeField(editable=False, verbose_name=datetime.datetime(2023, 12, 18, 18, 43, 46, 754054)),
        ),
    ]
