# Generated by Django 5.0 on 2023-12-20 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_alter_order_date_alter_order_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(editable=False, verbose_name=datetime.datetime(2023, 12, 20, 18, 16, 47, 87432)),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.TimeField(editable=False, verbose_name=datetime.datetime(2023, 12, 20, 18, 16, 47, 87432)),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='average_price',
            field=models.IntegerField(blank=True, default='Unknown', editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='rate',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50),
        ),
    ]
