# Generated by Django 5.0 on 2023-12-21 22:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_alter_order_date_alter_order_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='restaurant',
            field=models.ManyToManyField(to='pages.restaurant'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(editable=False, verbose_name=datetime.datetime(2023, 12, 22, 0, 12, 24, 205956)),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.TimeField(editable=False, verbose_name=datetime.datetime(2023, 12, 22, 0, 12, 24, 205956)),
        ),
    ]
