# Generated by Django 5.0 on 2023-12-21 22:22

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_remove_restaurant_product_product_restaurant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(editable=False, verbose_name=datetime.datetime(2023, 12, 22, 0, 22, 46, 908280)),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.TimeField(editable=False, verbose_name=datetime.datetime(2023, 12, 22, 0, 22, 46, 908280)),
        ),
        migrations.RemoveField(
            model_name='product',
            name='restaurant',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='average_price',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pages.restaurant'),
        ),
    ]
