# Generated by Django 5.0 on 2024-06-28 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_alter_order_created_at_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='averge_product_price',
            field=models.IntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateField(editable=False, null=True, verbose_name=datetime.datetime(2024, 6, 28, 19, 37, 40, 472329)),
        ),
    ]
