# Generated by Django 5.0 on 2024-06-28 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_restaurant_averge_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateField(editable=False, null=True, verbose_name=datetime.datetime(2024, 6, 28, 20, 3, 53, 446568)),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='averge_product_price',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
