# Generated by Django 5.0 on 2024-06-28 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_alter_order_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateField(editable=False, null=True, verbose_name=datetime.datetime(2024, 6, 28, 19, 48, 0, 879332)),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='averge_product_price',
            field=models.IntegerField(default=0, editable=False, null=True),
        ),
    ]
