# Generated by Django 5.0 on 2024-06-28 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0029_alter_order_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='averge_product_price',
            new_name='average_product_price',
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateField(editable=False, null=True, verbose_name=datetime.datetime(2024, 6, 28, 19, 45, 35, 956374)),
        ),
    ]
