# Generated by Django 5.0 on 2024-07-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0032_alter_order_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='restaurant',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='average_product_price',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True),
        ),
        migrations.DeleteModel(
            name='CartProduct',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
