# Generated by Django 5.0 on 2024-07-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0033_remove_order_restaurant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='average_product_price',
        ),
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
